# Generated by Django 4.2.4 on 2024-11-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grievance',
            name='category',
        ),
        migrations.AddField(
            model_name='grievance',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
